/* SPDX-License-Identifier: GPL-2.0 WITH Linux-syscall-note */
#ifndef UAPI_KVM_X86_PVM_TRACE_H
#define UAPI_KVM_X86_PVM_TRACE_H

#include <linux/bitops.h>

#define NMI_VECTOR				0x02
#define PVM_EXIT_REASONS_FAILED_VMENTRY		1025

#define PVM_EXIT_REASONS_SHIFT			16
#define PVM_EXIT_REASONS_SYSCALL		BIT(PVM_EXIT_REASONS_SHIFT)
#define PVM_EXIT_REASONS_HYPERCALL		(2UL << PVM_EXIT_REASONS_SHIFT)
#define PVM_EXIT_REASONS_ERETU			(3UL << PVM_EXIT_REASONS_SHIFT)
#define PVM_EXIT_REASONS_ERETS			(4UL << PVM_EXIT_REASONS_SHIFT)
#define PVM_EXIT_REASONS_INTERRUPT		(5UL << PVM_EXIT_REASONS_SHIFT)
#define PVM_EXIT_REASONS_INT80			(6UL << PVM_EXIT_REASONS_SHIFT)

#define PVM_EXIT_REASONS_HC_IRQ_WIN		(PVM_EXIT_REASONS_HYPERCALL + 1)
#define PVM_EXIT_REASONS_HC_IRQ_HALT		(PVM_EXIT_REASONS_HYPERCALL + 2)
#define PVM_EXIT_REASONS_HC_LOAD_PGTBL		(PVM_EXIT_REASONS_HYPERCALL + 3)
#define PVM_EXIT_REASONS_HC_TLB_FLUSH		(PVM_EXIT_REASONS_HYPERCALL + 4)
#define PVM_EXIT_REASONS_HC_TLB_FLUSH_CURRENT	(PVM_EXIT_REASONS_HYPERCALL + 5)
#define PVM_EXIT_REASONS_HC_TLB_INVLPG		(PVM_EXIT_REASONS_HYPERCALL + 6)
#define PVM_EXIT_REASONS_HC_LOAD_GS		(PVM_EXIT_REASONS_HYPERCALL + 7)
#define PVM_EXIT_REASONS_HC_RDMSR		(PVM_EXIT_REASONS_HYPERCALL + 8)
#define PVM_EXIT_REASONS_HC_WRMSR		(PVM_EXIT_REASONS_HYPERCALL + 9)
#define PVM_EXIT_REASONS_HC_LOAD_TLS		(PVM_EXIT_REASONS_HYPERCALL + 10)

#define PVM_EXIT_REASONS					\
	{ DE_VECTOR, "DE excp" },				\
	{ DB_VECTOR, "DB excp" },				\
	{ NMI_VECTOR, "NMI excp" },				\
	{ BP_VECTOR, "BP excp" },				\
	{ OF_VECTOR, "OF excp" },				\
	{ BR_VECTOR, "BR excp" },				\
	{ UD_VECTOR, "UD excp" },				\
	{ NM_VECTOR, "NM excp" },				\
	{ DF_VECTOR, "DF excp" },				\
	{ TS_VECTOR, "TS excp" },				\
	{ SS_VECTOR, "SS excp" },				\
	{ GP_VECTOR, "GP excp" },				\
	{ PF_VECTOR, "PF excp" },				\
	{ MF_VECTOR, "MF excp" },				\
	{ AC_VECTOR, "AC excp" },				\
	{ MC_VECTOR, "MC excp" },				\
	{ XM_VECTOR, "XM excp" },				\
	{ VE_VECTOR, "VE excp" },				\
	{ PVM_EXIT_REASONS_SYSCALL, "SYSCALL" },		\
	{ PVM_EXIT_REASONS_HYPERCALL, "HYPERCALL" },		\
	{ PVM_EXIT_REASONS_ERETU, "ERETU" },			\
	{ PVM_EXIT_REASONS_ERETS, "ERETS" },			\
	{ PVM_EXIT_REASONS_INTERRUPT, "INTERRUPT" },		\
	{ PVM_EXIT_REASONS_INT80, "INT80" },			\
	{ PVM_EXIT_REASONS_HC_IRQ_WIN, "HC_IRQ_WIN" },		\
	{ PVM_EXIT_REASONS_HC_IRQ_HALT, "HC_IRQ_HALT" },	\
	{ PVM_EXIT_REASONS_HC_LOAD_PGTBL, "HC_LOAD_PGTBL" },	\
	{ PVM_EXIT_REASONS_HC_TLB_FLUSH, "HC_TLB_FLUSH" },	\
	{ PVM_EXIT_REASONS_HC_TLB_FLUSH_CURRENT, "HC_TLB_FLUSH_CURRENT" },\
	{ PVM_EXIT_REASONS_HC_TLB_INVLPG, "HC_TLB_INVLPG" },	\
	{ PVM_EXIT_REASONS_HC_LOAD_GS, "HC_LOAD_GS" },		\
	{ PVM_EXIT_REASONS_HC_RDMSR, "HC_RDMSR" },		\
	{ PVM_EXIT_REASONS_HC_WRMSR, "HC_WRMSR" },		\
	{ PVM_EXIT_REASONS_HC_LOAD_TLS, "HC_LOAD_TLS" },	\
	{ PVM_EXIT_REASONS_FAILED_VMENTRY, "FAILED_VMENTRY" }

#endif /* UAPI_KVM_X86_PVM_TRACE_H */
